print(object)
print("Hello")
print(67)
print()
print(7.69)
name = "rohan"
print(name)
print(6, name)
print("Name:", name)
print(10-2)
print(f"Myself {name}.")
print("Hi my name is", end = " ")
print(name + ".")
print("wind", "rock", "water", sep = "-")
print("Hello\nWorld")
